name: CI on Windows

on: [push,pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby_version: [ '3.2', '3.3', '3.4' ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Run the default task
      run: |
        ridk exec bundle install
        ridk exec bundle exec rake
